/* ============================================================
   JEU 3 — Catalogue des PNJ « ambiants » (Cluedo)
   ------------------------------------------------------------
   Chaque PNJ a un id unique + une pose (x, y aux PIEDS du perso),
   un jeu de couleurs (haut, bas, peau, cheveux), une orientation
   (facing "front"/"left"/"right"), une posture (poseKind "stand"
   ou "sit"), un accessoire de métier optionnel, et surtout une
   activité (activity) qui remplace les bras et anime un geste
   caractéristique du métier.
   ============================================================ */
export const PNJ_ROOMS = {
  cantine: [
    { id: "cantine_nel",  nom: "Nel",  role: "Serveuse",
      pose: { x: 240, y: 400 }, color: "#8a5030", pants: "#3a2010", hair: "#5a3018",
      facing: "right", accessory: "apron", activity: "wipe",
      replique: "Je vois passer tout le monde ici. Personne ne mange plus à la même table depuis le mois dernier. Il y a comme une méfiance." },
    { id: "cantine_dor",  nom: "Dor",  role: "Cuisinier",
      pose: { x: 500, y: 400 }, color: "#c8d4e2", pants: "#3a2818", hair: "#1a1408",
      facing: "left", accessory: "apron", activity: "stir",
      replique: "Les rations viennent d'en-haut, du niveau 1. On me les donne, je les cuisine, je ne pose pas de questions. C'est comme ça depuis toujours." },
    { id: "cantine_via",  nom: "Via",  role: "Habitante",
      pose: { x: 780, y: 400 }, color: "#8a3820", pants: "#28303a", hair: "#3a1808",
      facing: "left", activity: "cup",
      replique: "Il paraît qu'un enfant a disparu au niveau 2. Personne ne veut me dire son nom. Tu crois qu'il est vraiment parti dehors ?" },
    { id: "cantine_mo",   nom: "Mo",   role: "Habitant hors-service",
      pose: { x: 140, y: 400 }, color: "#5a6270", pants: "#3a2818", hair: "#3a1808",
      facing: "right", activity: "crossed",
      replique: "Trente ans que je mange les mêmes rations. Le vieux Estev dit que le goût a changé après 2078. Moi je te dis : c'est le sel qu'on a baissé — c'est écrit nulle part, mais je le sens." },
    { id: "cantine_ela",  nom: "Ela",  role: "Enfant curieuse",
      pose: { x: 620, y: 400 }, color: "#c88060", pants: "#3a4048", hair: "#e8dfc8",
      facing: "left", activity: "cup",
      replique: "Ma mère dit que dehors c'est mort. Mais dans un livre de la salle des Archives, il y avait un dessin de champ de blé, page 42. Je l'ai regardé trois fois. Ensuite le livre a disparu." },
    { id: "cantine_bri",  nom: "Bri",  role: "Cuisinière en chef",
      pose: { x: 900, y: 400 }, color: "#e8dfc8", pants: "#3a2818", hair: "#8a3820",
      facing: "left", accessory: "apron", activity: "write",
      replique: "Chaque mois je compte les rations. Chaque mois, le compte est juste. Trop juste. Comme si quelqu'un connaissait à l'avance combien on serait à table." },
  ],
  infirmerie: [
    { id: "infirmerie_lin", nom: "Lin", role: "Médecin",
      pose: { x: 300, y: 400 }, color: "#7fd8ff", pants: "#3a4048", hair: "#5a4028",
      facing: "left", accessory: "coat", activity: "write",
      replique: "Je soigne des toux, des chutes, des yeux fatigués par les néons. Aucun cas de contamination extérieure depuis vingt ans. Aucun." },
    { id: "infirmerie_ora", nom: "Ora", role: "Aide-soignante",
      pose: { x: 700, y: 400 }, color: "#c8d4e2", pants: "#3a4048", hair: "#3a2818",
      facing: "right", accessory: "coat", activity: "clipboard",
      replique: "MARTINE contrôle nos dossiers médicaux. Tout ce que je note est envoyé à elle. Parfois, j'ai l'impression qu'elle réécrit ce que j'ai écrit." },
    { id: "infirmerie_mel", nom: "Mel", role: "Patiente au repos",
      pose: { x: 500, y: 388 }, color: "#8a5030", pants: "#3a4048", hair: "#c8a848",
      facing: "front", poseKind: "sit", activity: "cup",
      replique: "Je viens pour la grande fatigue. Lin dit que c'est mental. J'ai vu trois voisins passer par ce lit ce mois-ci. Personne n'en a reparlé après." },
  ],
  rumeurs: [
    { id: "rumeurs_boa", nom: "Boa", role: "Habitante en visite",
      pose: { x: 340, y: 460 }, color: "#c88060", pants: "#3a2010", hair: "#5a3018",
      facing: "left", activity: "crossed",
      replique: "Je viens ici toutes les semaines. Les papiers sur le panneau changent, mais la même main les écrit. C'est toujours la même écriture — trop régulière pour être humaine." },
    { id: "rumeurs_tas", nom: "Tas", role: "Adolescent lecteur",
      pose: { x: 720, y: 460 }, color: "#3a80c8", pants: "#28303a", hair: "#1a1408",
      facing: "right", activity: "cup",
      replique: "On m'a dit qu'un vieux message était affiché ici en 2074. Signé « L.V. ». Je l'ai jamais vu. Ma grand-mère l'a vu. Elle est morte l'année d'après." },
    { id: "rumeurs_hen", nom: "Hen", role: "Vieil archiviste retraité",
      pose: { x: 1080, y: 460 }, color: "#5a4028", pants: "#3a2010", hair: "#e8dfc8", skin: "#c8a888",
      facing: "left", activity: "write",
      replique: "Je viens noter les affichages sur mon carnet. Trois papiers ont disparu la nuit dernière — remplacés par des copies presque identiques. Presque." },
  ],
  atelier: [
    { id: "atelier_kev",  nom: "Kev",  role: "Ingénieur systèmes",
      pose: { x: 260, y: 400 }, color: "#3a4048", pants: "#28303a", hair: "#2a2018",
      facing: "left", accessory: "toolbelt", activity: "wrench",
      replique: "MARTINE tourne sur des serveurs du niveau -3. J'y suis descendu une fois pour une maintenance. Ce n'est pas une simple IA — quelqu'un l'a modifiée après 2050." },
    { id: "atelier_tam",  nom: "Tam",  role: "Mécanicienne",
      pose: { x: 520, y: 400 }, color: "#5a4028", pants: "#3a2010", hair: "#8a3820",
      facing: "right", accessory: "hardhat", activity: "hammer",
      replique: "Je répare des ventilos et des pompes toute la journée. Les filtres sont neufs — trop neufs. Pourquoi refaire des filtres à air si l'air dehors est empoisonné ?" },
    { id: "atelier_yon",  nom: "Yon",  role: "Électricien",
      pose: { x: 780, y: 400 }, color: "#c8a848", pants: "#3a2818", hair: "#3a1808",
      facing: "right", accessory: "toolbelt", activity: "torch",
      replique: "Le réseau électrique est stable — sauf tous les 40 jours pile. Coupure d'une minute, exactement. Ça vient d'en haut, pas d'en bas. Cherche pas plus loin, on te dira que c'est normal." },
    { id: "atelier_bel",  nom: "Bel",  role: "Apprentie",
      pose: { x: 400, y: 400 }, color: "#5eff9e", pants: "#3a4048", hair: "#c8a848",
      facing: "left", activity: "clipboard",
      replique: "Kev me forme sur les schémas électriques. Il a dessiné un plan des câbles qui montent au niveau -3. Il l'a caché derrière le tableau 4A. Cherche pas, je te dirai rien de plus." },
    { id: "atelier_gus",  nom: "Gus",  role: "Contremaître",
      pose: { x: 900, y: 400 }, color: "#8a5030", pants: "#3a2010", hair: "#e8dfc8", skin: "#c8a888",
      facing: "left", accessory: "coat", activity: "write",
      replique: "Je note tout dans mon registre : chaque panne, chaque réparation. Depuis huit ans, aucune coupure n'a été signalée à MARTINE. J'obéis. Mais mon registre parle, lui." },
  ],
  chambreN24: [
    { id: "voisin_lior", nom: "Lior", role: "Insomniaque",
      pose: { x: 620, y: 400 }, color: "#3a80c8", pants: "#28303a", hair: "#1a1408",
      facing: "left", activity: "cup",
      replique: "Je dors plus. La nuit, je capte les vieux canaux radio du bunker. Il y a une voix féminine sur la bande 87 — ce n'est pas MARTINE. Elle chuchote un prénom : Kova. Personne ne veut m'écouter." },
  ],
  chambreN30: [
    { id: "voisin_yona", nom: "Yona", role: "Couturière",
      pose: { x: 640, y: 400 }, color: "#8a5030", pants: "#3a2010", hair: "#c8a848",
      facing: "left", accessory: "apron", activity: "write",
      replique: "Je refais tout le linge du bunker. Les rouleaux de tissu arrivent chaque mois par l'ascenseur. Neufs. Sentis frais. Si l'extérieur est mort depuis 40 ans, dis-moi qui tisse encore ce coton ?" },
  ],
  chambreN32: [
    { id: "voisin_estev", nom: "Estev", role: "Ancien enseignant",
      pose: { x: 640, y: 400 }, color: "#5a4028", pants: "#3a2818", hair: "#e8dfc8", skin: "#c8a888",
      facing: "front", poseKind: "sit", activity: "write",
      replique: "Ça fait trente ans que je compare les récits des Anciens aux archives officielles. J'ai trente carnets. À chaque coupure de 40 jours, une ligne d'archive change. MARTINE réécrit doucement notre passé. Je n'ose pas le publier." },
  ],
  chambreN24: [
    { id: "voisin_lior", nom: "Lior", role: "Insomniaque",
      pose: { x: 620, y: 400 }, color: "#3a80c8", pants: "#28303a", hair: "#1a1408",
      facing: "front", activity: "cup",
      replique: "Je dors plus. La nuit, je capte les vieux canaux radio du bunker. Il y a une voix féminine sur la bande 87 — ce n'est pas MARTINE. Elle chuchote un prénom : Kova. Personne ne veut m'écouter." },
  ],
  chambreN30: [
    { id: "voisin_yona", nom: "Yona", role: "Couturière",
      pose: { x: 640, y: 400 }, color: "#8a5030", pants: "#3a2010", hair: "#c8a848",
      facing: "front", accessory: "apron", activity: "write",
      replique: "Je refais tout le linge du bunker. Les rouleaux de tissu arrivent chaque mois par l'ascenseur. Neufs. Sentis frais. Si l'extérieur est mort depuis 40 ans, dis-moi qui tisse encore ce coton ?" },
  ],
  chambreN32: [
    { id: "voisin_estev", nom: "Estev", role: "Ancien enseignant",
      pose: { x: 640, y: 400 }, color: "#5a4028", pants: "#3a2818", hair: "#e8dfc8", skin: "#c8a888",
      facing: "front", poseKind: "sit", activity: "write",
      replique: "Ça fait trente ans que je compare les récits des Anciens aux archives officielles. J'ai trente carnets. À chaque coupure de 40 jours, une ligne d'archive change. MARTINE réécrit doucement notre passé. Je n'ose pas le publier." },
  ],
  chapelle: [
    { id: "chapelle_anselme", nom: "Anselme", role: "Ancien",
      pose: { x: 260, y: 388 }, color: "#5a3818", pants: "#3a2010", hair: "#f0e4c8", skin: "#c8a888",
      facing: "front", poseKind: "sit", accessory: "robe", activity: "pray",
      replique: "J'ai vécu à la surface, jeune. Il y avait des oiseaux. Aujourd'hui on nous dit qu'il n'y a plus rien. Je ne sais plus qui croire." },
    { id: "chapelle_iris",   nom: "Iris",    role: "Fidèle",
      pose: { x: 760, y: 400 }, color: "#8a5030", pants: "#5a4028", hair: "#8a5030",
      facing: "left", accessory: "robe", activity: "pray",
      replique: "MARTINE nous protège. Elle a toujours dit la vérité. Ceux qui doutent finissent par disparaître — signe qu'ils avaient tort, non ?" },
  ],
};
